#!/usr/bin/env python3
"""
Build the static bundle for SAGA from the CMS pages.

    python3 static/build.py

The bundle is the whole CMS, running with no Node behind it. All three pages
are copied verbatim apart from the mechanical transforms below, so the demo
cannot drift from the real thing:

  - index.html is public/index.html, the Configurations page, so the bundle
    opens where the CMS opens
  - absolute /shared/... script paths become relative, so the bundle works
    from a subdirectory
  - shared/offline-api.js is injected into every page, answering the /api/...
    fetch calls from local data
  - data/sequences.js and data/configs.js carry the seed records as globals
    rather than JSON files, because fetch() of a local file is blocked on
    file:// and the bundle has to work there too
  - every page gets a banner saying saves are local only
  - the player gets an example picker and auto-loads the first sequence
  - the Google Fonts link and the favicon request are stripped, so the bundle
    makes no external requests at all

The output is static/dist/. Nothing in the repo's own public/ or shared/ is
changed by this script.
"""

import json
import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'public')
SHARED = os.path.join(ROOT, 'shared')
STATIC = os.path.join(ROOT, 'static')
DIST = os.path.join(STATIC, 'dist')

SHARED_FILES = ['catalogue.js', 'event-types.js', 'sequence-validator.js']

# public/index.html is the CMS's own home page, so it becomes the bundle's.
PAGES = [
    ('index.html', 'index.html'),
    ('sequences.html', 'sequences.html'),
    ('player.html', 'player.html'),
]

LOCAL_ONLY_NOTICE = (
    'Offline bundle. There is no server behind this, so everything you create '
    'or edit here is saved in your own browser only. Nothing is shared, and '
    'nothing survives clearing site data.'
)


def build():
    if os.path.isdir(DIST):
        shutil.rmtree(DIST)
    os.makedirs(os.path.join(DIST, 'shared'))
    os.makedirs(os.path.join(DIST, 'data'))

    # --- shared modules, copied verbatim --------------------------------
    for name in SHARED_FILES:
        shutil.copy(os.path.join(SHARED, name), os.path.join(DIST, 'shared', name))
    shutil.copy(os.path.join(STATIC, 'shared', 'offline-api.js'),
                os.path.join(DIST, 'shared', 'offline-api.js'))

    # --- seed data, as globals rather than fetched files ----------------
    with open(os.path.join(ROOT, 'examples', 'steuart-example-sequences.json')) as f:
        data = json.load(f)

    write_seed(
        'sequences.js', 'window.TISeedSequences', {'sequences': data['sequences']},
        'The worked example sequences.',
        'examples/steuart-example-sequences.json')

    with open(os.path.join(ROOT, 'examples', 'live-configs-2026-09-03.json')) as f:
        live = json.load(f)

    write_seed(
        'configs.js', 'window.TISeedConfigs', live,
        'The four-field configs as they stood on the live service, 3 Sep 2026.',
        'examples/live-configs-2026-09-03.json')

    # --- the logo -------------------------------------------------------
    logo = os.path.join(SRC, 'ti-logo.png')
    if os.path.exists(logo):
        shutil.copy(logo, os.path.join(DIST, 'ti-logo.png'))
    else:
        raise SystemExit('public/ti-logo.png is missing, put the real logo there first')

    # --- the three pages ------------------------------------------------
    for src_name, out_name in PAGES:
        with open(os.path.join(SRC, src_name)) as f:
            html = f.read()
        html = transform(html, src_name)
        with open(os.path.join(DIST, out_name), 'w') as f:
            f.write(html)

    report()


def write_seed(filename, global_name, payload, what, source):
    with open(os.path.join(DIST, 'data', filename), 'w') as f:
        f.write(
            '/* %s\n'
            '   Baked in so the bundle needs no server and no network.\n'
            '   Generated by static/build.py, do not edit by hand: edit\n'
            '   %s instead. */\n'
            '%s = ' % (what, source, global_name))
        json.dump(payload, f, indent=2)
        f.write(';\n')


def transform(html, name):
    # Relative script paths so the bundle survives being served from a
    # subdirectory, which is how most hosts unpack a zip.
    html = html.replace('src="/shared/', 'src="shared/')

    # No external requests. A Web Object behind a corporate firewall, or an
    # exhibition laptop with no network, must not be waiting on Google Fonts.
    # The pages already declare a system fallback stack after Inter.
    html = re.sub(
        r'\s*<link href="https://fonts\.googleapis\.com[^>]*>',
        '', html)
    if 'fonts.googleapis.com' in html:
        raise SystemExit('a Google Fonts reference survived in ' + name)

    # An empty data: icon stops the browser asking the host for /favicon.ico,
    # which is the last request the bundle would otherwise make.
    html = html.replace(
        '<meta name="viewport"',
        '<link rel="icon" href="data:,">\n    <meta name="viewport"', 1)

    # The seeds and the shim have to load before the page's own script. The
    # shim reads TIEvents and TIValidator when they exist, so it goes last.
    if '<script src="shared/catalogue.js"></script>' in html:
        # The builder and the player: shared modules already present.
        html = html.replace(
            '<script src="shared/catalogue.js"></script>',
            '<script src="data/sequences.js"></script>\n'
            '    <script src="data/configs.js"></script>\n'
            '    <script src="shared/catalogue.js"></script>',
            1)
        # The builder loads the validator, the player does not, so anchor to
        # whichever shared module comes last on this page.
        for anchor in ['<script src="shared/sequence-validator.js"></script>',
                       '<script src="shared/event-types.js"></script>']:
            if anchor in html:
                html = html.replace(
                    anchor, anchor + '\n    <script src="shared/offline-api.js"></script>', 1)
                break
        else:
            raise SystemExit('no shared module to anchor the shim to in ' + name)
    else:
        # The Configurations page loads no shared modules, so the seeds and the
        # shim go in just before its own inline script.
        anchor = '    <script>'
        if anchor not in html:
            raise SystemExit('no inline script to anchor the shim to in ' + name)
        html = html.replace(
            anchor,
            '    <script src="data/sequences.js"></script>\n'
            '    <script src="data/configs.js"></script>\n'
            '    <script src="shared/offline-api.js"></script>\n' + anchor,
            1)

    # Cross-page links are already relative and all three pages exist.

    if name == 'player.html':
        html = add_player_picker(html)

    html = add_offline_notice(html, LOCAL_ONLY_NOTICE)

    return html


def add_offline_notice(html, text):
    """Drop a banner in above the page's grid. All three pages use the same
    .grid wrapper, so one marker covers them."""
    banner = (
        '<div style="max-width:1500px;margin:0 auto;padding:0 20px 20px">'
        '<div style="background:rgba(245,158,11,0.12);border:1px solid #f59e0b;'
        'color:#fcd34d;border-radius:10px;padding:12px 16px;font-size:0.85rem">'
        + text + '</div></div>\n        ')
    marker = '<div class="grid">'
    if marker not in html:
        raise SystemExit('could not find the grid to place the offline notice above')
    return html.replace(marker, banner + marker, 1)


def add_player_picker(html):
    """The player normally takes a User ID from the builder's saved list. In
    the bundle there is no list to come from, so offer the examples directly
    and open on the first one."""
    # white-space:normal on the buttons, because the example names are long
    # enough to force a horizontal scrollbar at phone width otherwise.
    picker_markup = '''                    <div class="field" style="flex:0 0 100%">
                        <label>Example sequences</label>
                        <div id="examples" style="display:flex;gap:8px;flex-wrap:wrap"></div>
                    </div>
                    <style>
                        #examples .btn {
                            white-space: normal;
                            text-align: left;
                            flex: 1 1 200px;
                            min-width: 0;
                            line-height: 1.3;
                        }
                    </style>
'''
    marker = '                    <button class="btn btn-primary" id="load">Load</button>\n'
    if marker not in html:
        raise SystemExit('could not find the Load button to add the picker beside')
    html = html.replace(marker, marker + picker_markup, 1)

    picker_js = '''
        // ---- offline bundle: quick picks for the baked-in examples ----
        (function () {
            var host = document.getElementById('examples');
            if (!host || !window.TISeedSequences) return;

            function paint() {
                host.innerHTML = '';
                (window.TISeedSequences.sequences || []).forEach(function (s) {
                    var b = document.createElement('button');
                    b.className = 'btn btn-secondary';
                    b.textContent = s.name || s.user_id;
                    b.addEventListener('click', function () {
                        el.user.value = s.user_id;
                        load();
                    });
                    host.appendChild(b);
                });
            }

            paint();

            // Open on the first example rather than an empty screen.
            if (!new URLSearchParams(location.search).get('user')) {
                var first = (window.TISeedSequences.sequences || [])[0];
                if (first) { el.user.value = first.user_id; load(); }
            }
        })();
'''
    tail = "        var preset = new URLSearchParams(location.search).get('user');"
    if tail not in html:
        raise SystemExit('could not find the player bootstrap to append the picker to')
    return html.replace(tail, picker_js + '\n' + tail, 1)


def report():
    total = 0
    print('Built ' + os.path.relpath(DIST, ROOT))
    for base, _, files in os.walk(DIST):
        for f in sorted(files):
            p = os.path.join(base, f)
            size = os.path.getsize(p)
            total += size
            print('  %-34s %8d bytes' % (os.path.relpath(p, DIST), size))
    print('  %-34s %8d bytes' % ('TOTAL', total))


if __name__ == '__main__':
    build()
